---
name: "build"
run-name: "${{ github.workflow }} triggered by ${{ github.actor }}"

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: "ubuntu-22.04"
    strategy:
      matrix:
        version: ["0.4.8"]
        binary: ["goss-linux-amd64"]
    steps:
      - name: "fetch"
        run: |
          curl --location "https://github.com/goss-org/goss/releases/download/v${{ matrix.version }}/${{ matrix.binary }}" --output "${{ matrix.binary }}"
          curl --location "https://github.com/goss-org/goss/releases/download/v${{ matrix.version }}/${{ matrix.binary }}.sha256" --output "${{ matrix.binary }}.sha256"
          sha256sum --check "${{ matrix.binary }}.sha256"

      - name: "build"
        run: |
          mkdir -p goss/{DEBIAN,usr/bin}
          cat >goss/DEBIAN/control <<EOF
          Package: goss
          Version: ${{ matrix.version }}
          Maintainer: Mark Mercado <mamercad@gmail.com>
          Architecture: all
          Description: https://github.com/goss-org/goss
          EOF
          cp "${{ matrix.binary }}" goss/usr/bin/goss
          dpkg-deb --build goss
