---
name: "build"
run-name: "${{ github.workflow }} triggered by ${{ github.actor }}"

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: "ubuntu-22.04"
    strategy:
      matrix:
        version: ["0.4.8"]
        os: ["linux"]
        revision: ["1"]
        arch: ["amd64"]
    steps:
      - name: "fetch"
        run: |
          curl --location "https://github.com/goss-org/goss/releases/download/v${{ matrix.version }}/goss-${{ matrix.os }}-${{ matrix.arch }}" --output "goss-${{ matrix.os }}-${{ matrix.arch }}"
          curl --location "https://github.com/goss-org/goss/releases/download/v${{ matrix.version }}/goss-${{ matrix.os }}-${{ matrix.arch }}.sha256" --output "goss-${{ matrix.os }}-${{ matrix.arch }}.sha256"
          sha256sum --check "goss-${{ matrix.os }}-${{ matrix.arch }}.sha256"

      - name: "build"
        run: |
          build_dir="goss_${{ matrix.version }}-${{ matrix.revision }}_${{ matrix.arch }}"
          mkdir "${build_dir}"
          mkdir "${build_dir}/DEBIAN"
          mkdir -p "${build_dir}/usr/bin"
          cat >"${build_dir}/DEBIAN/control" <<EOF
          Package: goss
          Version: ${{ matrix.version }}
          Maintainer: Mark Mercado <mamercad@gmail.com>
          Architecture: all
          Description: https://github.com/goss-org/goss
          EOF
          cp "goss-${{ matrix.os }}-${{ matrix.arch }}" "${build_dir}/usr/bin/goss"
          dpkg-deb --build "${build_dir}"
