---
name: "build"
run-name: "${{ github.actor }} triggered ${{ github.workflow }}"

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: "ubuntu-22.04"
    strategy:
      matrix:
        - version: "v0.4.8"
          binary: "goss-linux-amd64"
    steps:
      - name: "fetch"
        run: |
          curl --location "https://github.com/goss-org/goss/releases/download/${{ matrix.version }}/${{ matrix.binary }}" --output "${{ matrix.binary }}"
          curl --location "https://github.com/goss-org/goss/releases/download/${{ matrix.version }}/${{ matrix.binary }}.sha256" --output "${{ matrix.binary }}.sha256"
